### ISSUE TITLE
Add support for joystick

### ISSUE THREAD

**Issue by thealphadollar** [thealphadollar/brkout#23]
Add support for joystick for the movement in game.

**Comment by prashantramnani** [comment]
As a part of kwoc, I would like to work on this issue.

**Comment by thealphadollar** [comment]
Assigned to @prashantramnani

**Comment by prashantramnani** [comment]
relative import has been used in the scripts. Can I change them to absolute?relative isn't working for me.

**Comment by thealphadollar** [comment]
I would suggest making the code such that it works in both ways.

That is, use try and except and if relative import gives an error, use absolute import.

**Comment by prashantramnani** [comment]
Shall I create an issue for that?

**Comment by thealphadollar** [comment]
fixed via #37
