### ISSUE TITLE
Ask the player for his name

### ISSUE THREAD

**Issue by thealphadollar** [thealphadollar/brkout#25]
Add a box where the player can enter his name.

**Comment by deepak2431** [comment]
I would like to work on this issue.

**Comment by pixlmaster** [comment]
the name should be displayed somewhere too? and the said box should be on start screen or a separate screen?

**Comment by thealphadollar** [comment]
@deepak2431 Are you working on this issue?

@pixlmaster If he is working then you shouldn't work. And yes, it is upon the developer where we wishes to place it. We can make modifications later. Coding is the harder part.

**Comment by pixlmaster** [comment]
oh sorry , i saw the empty assigned column and came here

**Comment by amrit-choudhary** [comment]
Can you please assign me this?

**Comment by thealphadollar** [comment]
Since Deepak doesn't seem to be working on this; you can :)
