### ISSUE TITLE
Muting Dosen't work in game-screen/loop

### ISSUE THREAD

**Issue by pixlmaster** [thealphadollar/brkout#32]
Pressing The mute button on start screen only mutes the music of start screen. and the music in game screen and end-screen still plays.

**Comment by thealphadollar** [comment]
@pixlmaster Please provide description of the issue so others can understand it as well.

**Comment by pixlmaster** [comment]
@thealphadollar updated issue description, also submitted a PR fixing the same.

**Comment by thealphadollar** [comment]
fixed via #35
